## Abilita il caricamento delle definizioni all'avvio
management.load_definitions = /etc/rabbitmq/definitions.json

## Limiti di memoria
vm_memory_high_watermark.relative = 0.6

## Logging
log.console = true
log.console.level = warning
